"""Baseline schema marker (Phase 1).

Revision ID: 001_baseline
Revises:
Create Date: 2026-07-20

Schema is currently managed by ``models.init_db()`` / ``Base.metadata.create_all``.
This revision documents the Alembic starting point so future diffs can be
autogenerated against PostgreSQL (or SQLite) without rewriting history.
"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Intentionally empty: create_all currently manages schema.
    # Alembic is ready for future autogenerate diffs from this baseline.
    pass


def downgrade() -> None:
    # Intentionally empty — see upgrade().
    pass
