/**
 * Bozdemir Makine — Üretim Planlama Master Data
 * Tasarım & Montaj: montaj grupları (ortak)
 * Talaşlı imalat (CNC): ürün grupları (tezgâh ayarı)
 */

const MASTER = {
  stages: [
    { id: "sales", name: "Satış & Pazarlama", color: "#0ea5e9", mode: "simple" },
    { id: "design", name: "Tasarım", color: "#6366f1", mode: "assembly_groups" },
    { id: "purchasing", name: "Satın Alma", color: "#f59e0b", mode: "simple" },
    {
      id: "production",
      name: "Üretim",
      color: "#ef4444",
      mode: "sub_stages",
      subStages: [
        { id: "machining", name: "Talaşlı İmalat", color: "#dc2626", mode: "product_groups" },
        { id: "welding", name: "Kaynak", color: "#ea580c", mode: "simple" },
        { id: "paint", name: "Boyahane", color: "#c2410c", mode: "simple" },
      ],
    },
    { id: "qc", name: "Kalite Kontrol", color: "#10b981", mode: "simple" },
    { id: "assembly", name: "Montaj & Otomasyon", color: "#8b5cf6", mode: "assembly_groups" },
  ],

  /** 7 makine tipi */
  machineTypes: [
    { id: "mt1", code: "RULO", name: "Rulo Açıcı / Doğrultucu" },
    { id: "mt2", code: "PRES", name: "Pres Hattı" },
    { id: "mt3", code: "KESIM", name: "Kesim Makinesi" },
    { id: "mt4", code: "BÜKÜM", name: "Büküm Makinesi" },
    { id: "mt5", code: "KAYNAK", name: "Kaynak İstasyonu" },
    { id: "mt6", code: "TRANSFER", name: "Transfer Sistemi" },
    { id: "mt7", code: "ÖZEL", name: "Özel Makine" },
  ],

  /** Tasarım + Montaj ortak grupları */
  assemblyGroups: [
    { id: "ag1", name: "Pinol Grubu", order: 1 },
    { id: "ag2", name: "Rulo Grubu", order: 2 },
    { id: "ag3", name: "Dişli Kutusu", order: 3 },
    { id: "ag4", name: "Şasi / Gövde", order: 4 },
    { id: "ag5", name: "Hidrolik Ünite", order: 5 },
    { id: "ag6", name: "Elektrik Panosu", order: 6 },
    { id: "ag7", name: "Otomasyon / PLC", order: 7 },
    { id: "ag8", name: "Güvenlik / Muhafaza", order: 8 },
  ],

  /** CNC — aynı Ø / aile peş peşe tezgâha */
  productGroups: [
    { id: "pg1", name: "Ø12–Ø18 Mil / Pim", diameter: "Ø18", family: "mil" },
    { id: "pg2", name: "Ø20–Ø30 Mil / Pim", diameter: "Ø25", family: "mil" },
    { id: "pg3", name: "Ø32–Ø50 Mil / Pim", diameter: "Ø40", family: "mil" },
    { id: "pg4", name: "Flanş / Kapak", diameter: "—", family: "flans" },
    { id: "pg5", name: "Rulman Yuvası", diameter: "—", family: "yuvasi" },
    { id: "pg6", name: "Dişli / Kayış Kasnağı", diameter: "—", family: "disli" },
    { id: "pg7", name: "Plaka / Tabla", diameter: "—", family: "plaka" },
  ],

  people: [
    { id: "p1", name: "Ahmet Yılmaz", unit: "Satış" },
    { id: "p2", name: "Elif Kara", unit: "Tasarım" },
    { id: "p3", name: "Can Demir", unit: "Tasarım" },
    { id: "p4", name: "Zeynep Aydın", unit: "Satın Alma" },
    { id: "p5", name: "Murat Çelik", unit: "CNC" },
    { id: "p6", name: "Hasan Korkmaz", unit: "Kaynak" },
    { id: "p7", name: "Ayşe Polat", unit: "Boyahane" },
    { id: "p8", name: "Burak Şahin", unit: "Kalite" },
    { id: "p9", name: "Deniz Arslan", unit: "Montaj" },
    { id: "p10", name: "Emre Koç", unit: "Otomasyon" },
  ],
};

function task(partial) {
  return {
    groupId: null,
    subStageId: null,
    actualStart: null,
    actualEnd: null,
    status: "planned",
    ...partial,
  };
}

/**
 * Örnek projeler — 21 Temmuz 2026’ya göre canlı dashboard/Gantt
 * Planlanan vs gerçekleşen farkları bilinçli bırakıldı.
 */
function createSampleProjects() {
  return [
    {
      id: "prj1",
      code: "PRJ-2026-014",
      name: "ABC Metal — Rulo Açıcı Hattı",
      machineTypeId: "mt1",
      customer: "ABC Metal Sanayi",
      status: "active",
      createdAt: "2026-05-01",
      tasks: [
        task({
          id: "t1",
          stageId: "sales",
          title: "Teklif & Sipariş Onayı",
          assigneeId: "p1",
          plannedStart: "2026-05-02",
          plannedEnd: "2026-05-08",
          actualStart: "2026-05-02",
          actualEnd: "2026-05-12",
          status: "done",
        }),
        /* —— Tasarım (montaj grupları) —— */
        task({
          id: "t2",
          stageId: "design",
          groupId: "ag1",
          title: "Pinol Grubu Tasarım",
          assigneeId: "p2",
          plannedStart: "2026-05-12",
          plannedEnd: "2026-05-16",
          actualStart: "2026-05-13",
          actualEnd: "2026-05-23",
          status: "done",
        }),
        task({
          id: "t3",
          stageId: "design",
          groupId: "ag2",
          title: "Rulo Grubu Tasarım",
          assigneeId: "p3",
          plannedStart: "2026-05-12",
          plannedEnd: "2026-05-20",
          actualStart: "2026-05-14",
          actualEnd: "2026-05-28",
          status: "done",
        }),
        task({
          id: "t4",
          stageId: "design",
          groupId: "ag3",
          title: "Dişli Kutusu Tasarım",
          assigneeId: "p2",
          plannedStart: "2026-05-17",
          plannedEnd: "2026-05-22",
          actualStart: "2026-05-24",
          actualEnd: "2026-06-05",
          status: "done",
        }),
        task({
          id: "t5",
          stageId: "design",
          groupId: "ag4",
          title: "Şasi / Gövde Tasarım",
          assigneeId: "p3",
          plannedStart: "2026-05-20",
          plannedEnd: "2026-05-27",
          actualStart: "2026-05-29",
          actualEnd: "2026-06-08",
          status: "done",
        }),
        task({
          id: "t5b",
          stageId: "design",
          groupId: "ag5",
          title: "Hidrolik Ünite Tasarım",
          assigneeId: "p2",
          plannedStart: "2026-05-26",
          plannedEnd: "2026-06-02",
          actualStart: "2026-06-06",
          actualEnd: "2026-06-14",
          status: "done",
        }),
        task({
          id: "t6",
          stageId: "design",
          groupId: "ag6",
          title: "Elektrik Panosu Tasarım",
          assigneeId: "p10",
          plannedStart: "2026-05-28",
          plannedEnd: "2026-06-04",
          actualStart: "2026-06-10",
          actualEnd: "2026-06-20",
          status: "done",
        }),
        task({
          id: "t6b",
          stageId: "design",
          groupId: "ag7",
          title: "Otomasyon / PLC Tasarım",
          assigneeId: "p10",
          plannedStart: "2026-06-02",
          plannedEnd: "2026-06-10",
          actualStart: "2026-06-15",
          actualEnd: "2026-06-28",
          status: "done",
        }),
        task({
          id: "t6c",
          stageId: "design",
          groupId: "ag8",
          title: "Güvenlik / Muhafaza Tasarım",
          assigneeId: "p3",
          plannedStart: "2026-06-05",
          plannedEnd: "2026-06-10",
          actualStart: "2026-06-20",
          actualEnd: "2026-06-27",
          status: "done",
        }),
        /* —— Satın alma —— */
        task({
          id: "t7",
          stageId: "purchasing",
          title: "Malzeme & Standart Parça Siparişi",
          assigneeId: "p4",
          plannedStart: "2026-06-08",
          plannedEnd: "2026-06-20",
          actualStart: "2026-06-12",
          actualEnd: "2026-07-02",
          status: "done",
        }),
        /* —— CNC ürün grupları (Ø peş peşe) —— */
        task({
          id: "t8",
          stageId: "production",
          subStageId: "machining",
          groupId: "pg1",
          title: "Ø18 Pinol Mili CNC",
          assigneeId: "p5",
          plannedStart: "2026-07-03",
          plannedEnd: "2026-07-06",
          actualStart: "2026-07-03",
          actualEnd: "2026-07-09",
          status: "done",
        }),
        task({
          id: "t9",
          stageId: "production",
          subStageId: "machining",
          groupId: "pg1",
          title: "Ø16 Rulo Mili CNC",
          assigneeId: "p5",
          plannedStart: "2026-07-06",
          plannedEnd: "2026-07-09",
          actualStart: "2026-07-09",
          actualEnd: "2026-07-14",
          status: "done",
        }),
        task({
          id: "t9b",
          stageId: "production",
          subStageId: "machining",
          groupId: "pg1",
          title: "Ø18 Pim Seti CNC",
          assigneeId: "p5",
          plannedStart: "2026-07-09",
          plannedEnd: "2026-07-11",
          actualStart: "2026-07-14",
          actualEnd: null,
          status: "active",
        }),
        task({
          id: "t10",
          stageId: "production",
          subStageId: "machining",
          groupId: "pg4",
          title: "Flanş / Kapak İşleme",
          assigneeId: "p5",
          plannedStart: "2026-07-11",
          plannedEnd: "2026-07-15",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t10b",
          stageId: "production",
          subStageId: "machining",
          groupId: "pg5",
          title: "Rulman Yuvası İşleme",
          assigneeId: "p5",
          plannedStart: "2026-07-15",
          plannedEnd: "2026-07-18",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t10c",
          stageId: "production",
          subStageId: "machining",
          groupId: "pg6",
          title: "Dişli / Kasnak CNC",
          assigneeId: "p5",
          plannedStart: "2026-07-18",
          plannedEnd: "2026-07-22",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        /* —— Kaynak / Boya —— */
        task({
          id: "t11",
          stageId: "production",
          subStageId: "welding",
          title: "Şasi Kaynak",
          assigneeId: "p6",
          plannedStart: "2026-07-08",
          plannedEnd: "2026-07-15",
          actualStart: "2026-07-10",
          actualEnd: null,
          status: "active",
        }),
        task({
          id: "t12",
          stageId: "production",
          subStageId: "paint",
          title: "Boyahane",
          assigneeId: "p7",
          plannedStart: "2026-07-16",
          plannedEnd: "2026-07-20",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t13",
          stageId: "qc",
          title: "Parça & Montaj Öncesi KK",
          assigneeId: "p8",
          plannedStart: "2026-07-20",
          plannedEnd: "2026-07-23",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        /* —— Montaj (aynı tasarım grupları) —— */
        task({
          id: "t14",
          stageId: "assembly",
          groupId: "ag1",
          title: "Pinol Grubu Montaj",
          assigneeId: "p9",
          plannedStart: "2026-07-24",
          plannedEnd: "2026-07-28",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t15",
          stageId: "assembly",
          groupId: "ag2",
          title: "Rulo Grubu Montaj",
          assigneeId: "p9",
          plannedStart: "2026-07-27",
          plannedEnd: "2026-07-31",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t16",
          stageId: "assembly",
          groupId: "ag3",
          title: "Dişli Kutusu Montaj",
          assigneeId: "p9",
          plannedStart: "2026-07-30",
          plannedEnd: "2026-08-04",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t16b",
          stageId: "assembly",
          groupId: "ag4",
          title: "Şasi / Gövde Montaj",
          assigneeId: "p9",
          plannedStart: "2026-08-03",
          plannedEnd: "2026-08-07",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t16c",
          stageId: "assembly",
          groupId: "ag5",
          title: "Hidrolik Ünite Montaj",
          assigneeId: "p9",
          plannedStart: "2026-08-05",
          plannedEnd: "2026-08-08",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t16d",
          stageId: "assembly",
          groupId: "ag6",
          title: "Elektrik Panosu Montaj",
          assigneeId: "p10",
          plannedStart: "2026-08-07",
          plannedEnd: "2026-08-11",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t17",
          stageId: "assembly",
          groupId: "ag7",
          title: "Otomasyon / PLC Entegrasyon",
          assigneeId: "p10",
          plannedStart: "2026-08-10",
          plannedEnd: "2026-08-18",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t17b",
          stageId: "assembly",
          groupId: "ag8",
          title: "Güvenlik / Muhafaza Montaj",
          assigneeId: "p9",
          plannedStart: "2026-08-15",
          plannedEnd: "2026-08-19",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
      ],
    },

    {
      id: "prj2",
      code: "PRJ-2026-018",
      name: "Delta Sac — Kesim Makinesi",
      machineTypeId: "mt3",
      customer: "Delta Sac A.Ş.",
      status: "active",
      createdAt: "2026-06-01",
      tasks: [
        task({
          id: "t20",
          stageId: "sales",
          title: "Sipariş Onayı",
          assigneeId: "p1",
          plannedStart: "2026-06-02",
          plannedEnd: "2026-06-05",
          actualStart: "2026-06-02",
          actualEnd: "2026-06-06",
          status: "done",
        }),
        task({
          id: "t21",
          stageId: "design",
          groupId: "ag4",
          title: "Şasi / Gövde Tasarım",
          assigneeId: "p2",
          plannedStart: "2026-06-08",
          plannedEnd: "2026-06-15",
          actualStart: "2026-06-09",
          actualEnd: "2026-06-28",
          status: "done",
        }),
        task({
          id: "t22",
          stageId: "design",
          groupId: "ag1",
          title: "Pinol Grubu Tasarım",
          assigneeId: "p3",
          plannedStart: "2026-06-10",
          plannedEnd: "2026-06-14",
          actualStart: "2026-06-11",
          actualEnd: "2026-06-20",
          status: "done",
        }),
        task({
          id: "t22b",
          stageId: "design",
          groupId: "ag3",
          title: "Dişli Kutusu Tasarım",
          assigneeId: "p2",
          plannedStart: "2026-06-16",
          plannedEnd: "2026-06-22",
          actualStart: "2026-06-25",
          actualEnd: null,
          status: "active",
        }),
        task({
          id: "t22c",
          stageId: "design",
          groupId: "ag6",
          title: "Elektrik Panosu Tasarım",
          assigneeId: "p10",
          plannedStart: "2026-06-20",
          plannedEnd: "2026-06-27",
          actualStart: "2026-07-01",
          actualEnd: null,
          status: "active",
        }),
        task({
          id: "t22d",
          stageId: "purchasing",
          title: "Malzeme Siparişi",
          assigneeId: "p4",
          plannedStart: "2026-06-28",
          plannedEnd: "2026-07-10",
          actualStart: "2026-07-05",
          actualEnd: null,
          status: "active",
        }),
        task({
          id: "t23",
          stageId: "production",
          subStageId: "machining",
          groupId: "pg2",
          title: "Ø25 Kesim Mili CNC",
          assigneeId: "p5",
          plannedStart: "2026-07-22",
          plannedEnd: "2026-07-25",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t23b",
          stageId: "production",
          subStageId: "machining",
          groupId: "pg2",
          title: "Ø28 Rulman Mili CNC",
          assigneeId: "p5",
          plannedStart: "2026-07-25",
          plannedEnd: "2026-07-28",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t23c",
          stageId: "production",
          subStageId: "machining",
          groupId: "pg7",
          title: "Tabla / Plaka İşleme",
          assigneeId: "p5",
          plannedStart: "2026-07-28",
          plannedEnd: "2026-07-31",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t23d",
          stageId: "production",
          subStageId: "welding",
          title: "Gövde Kaynak",
          assigneeId: "p6",
          plannedStart: "2026-07-26",
          plannedEnd: "2026-08-02",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t23e",
          stageId: "production",
          subStageId: "paint",
          title: "Boyahane",
          assigneeId: "p7",
          plannedStart: "2026-08-03",
          plannedEnd: "2026-08-06",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t23f",
          stageId: "qc",
          title: "Kalite Kontrol",
          assigneeId: "p8",
          plannedStart: "2026-08-06",
          plannedEnd: "2026-08-08",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t24",
          stageId: "assembly",
          groupId: "ag1",
          title: "Pinol Grubu Montaj",
          assigneeId: "p9",
          plannedStart: "2026-08-10",
          plannedEnd: "2026-08-13",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t24b",
          stageId: "assembly",
          groupId: "ag4",
          title: "Şasi Montaj",
          assigneeId: "p9",
          plannedStart: "2026-08-12",
          plannedEnd: "2026-08-16",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t24c",
          stageId: "assembly",
          groupId: "ag7",
          title: "PLC Entegrasyon",
          assigneeId: "p10",
          plannedStart: "2026-08-15",
          plannedEnd: "2026-08-22",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
      ],
    },

    {
      id: "prj3",
      code: "PRJ-2026-021",
      name: "Nova Pres — 160t Pres Hattı",
      machineTypeId: "mt2",
      customer: "Nova Pres Ltd.",
      status: "active",
      createdAt: "2026-07-01",
      tasks: [
        task({
          id: "t30",
          stageId: "sales",
          title: "Sipariş Onayı",
          assigneeId: "p1",
          plannedStart: "2026-07-02",
          plannedEnd: "2026-07-06",
          actualStart: "2026-07-02",
          actualEnd: "2026-07-07",
          status: "done",
        }),
        task({
          id: "t31",
          stageId: "design",
          groupId: "ag4",
          title: "Şasi / Gövde Tasarım",
          assigneeId: "p2",
          plannedStart: "2026-07-08",
          plannedEnd: "2026-07-15",
          actualStart: "2026-07-09",
          actualEnd: null,
          status: "active",
        }),
        task({
          id: "t32",
          stageId: "design",
          groupId: "ag1",
          title: "Pinol Grubu Tasarım",
          assigneeId: "p3",
          plannedStart: "2026-07-10",
          plannedEnd: "2026-07-14",
          actualStart: "2026-07-11",
          actualEnd: null,
          status: "active",
        }),
        task({
          id: "t33",
          stageId: "design",
          groupId: "ag5",
          title: "Hidrolik Ünite Tasarım",
          assigneeId: "p2",
          plannedStart: "2026-07-16",
          plannedEnd: "2026-07-22",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t34",
          stageId: "design",
          groupId: "ag6",
          title: "Elektrik Panosu Tasarım",
          assigneeId: "p10",
          plannedStart: "2026-07-18",
          plannedEnd: "2026-07-25",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t35",
          stageId: "purchasing",
          title: "Malzeme Siparişi",
          assigneeId: "p4",
          plannedStart: "2026-07-26",
          plannedEnd: "2026-08-08",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t36",
          stageId: "production",
          subStageId: "machining",
          groupId: "pg3",
          title: "Ø40 Pres Mili CNC",
          assigneeId: "p5",
          plannedStart: "2026-08-10",
          plannedEnd: "2026-08-14",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t37",
          stageId: "assembly",
          groupId: "ag1",
          title: "Pinol Grubu Montaj",
          assigneeId: "p9",
          plannedStart: "2026-08-25",
          plannedEnd: "2026-08-28",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
        task({
          id: "t38",
          stageId: "assembly",
          groupId: "ag4",
          title: "Şasi Montaj",
          assigneeId: "p9",
          plannedStart: "2026-08-27",
          plannedEnd: "2026-09-02",
          actualStart: null,
          actualEnd: null,
          status: "planned",
        }),
      ],
    },
  ];
}

const STORAGE_KEY = "bozdemir_planlama_v2";

function loadState() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw);
  } catch (_) {}
  return { projects: createSampleProjects() };
}

function saveState(state) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
}
